config/routes.rb
Rails.application.routes.draw do
  root "application#index"

  get "login", to: redirect("/auth/discord"), as: "login"
  get "logout", to: "sessions#destroy", as: "logout"
  get "auth/:provider/callback", to: "sessions#create"
  get "auth/failure", to: "application#index"
  get "me", to: "me#show", as: "me"

  resources :matches, only: %w(show index new create) do
    get "reserve", to: "matches#reserve"
    get "relinquish", to: "matches#relinquish"
  end
end

app/models/match.rb
class Match < ApplicationRecord
  belongs_to :game
  belongs_to :host, class_name: "User", foreign_key: "user_id"
  belongs_to :webhook

  has_many :reservations
  has_many :users, through: :reservations

  after_create :reserve_host
  before_create :generate_name

  DEFAULT_START = ActiveSupport::TimeZone["EST"].parse("#{Time.zone.now.to_date} 6pm")

  def to_param
    "#{id}-#{name.parameterize}"
  end

  def players
    reservations.includes(:user).where(ringer: false).map{|r| r.user}
  end

  def ringers
    reservations.includes(:user).where(ringer: true).map{|r| r.user}
  end

  def reserve(user)
    begin
      slot = reservations.find_or_initialize_by(user_id: user.id)
      slot.ringer = full? if slot.ringer || slot.new_record?
      notify = slot.ringer_changed? || slot.new_record?
      slot.save
      Notifications.player_reserved(self, user) if notify
    rescue ActiveRecord::RecordNotUnique
      false
    end
  end

  def full?
    players.count >= slots
  end

  def reserved?(user)
    reservations.where(user_id: user.id).present?
  end

  def ringer?(user)
    reservations.where(user_id: user.id, ringer: true).present?
  end

  def relinquish(user)
    reservations.where(user_id: user.id).first&.destroy
    Notifications.player_relinquished(self)
  end

  def slots_remaining
    slots - players.count
  end

  def formatted_start
    start_time.strftime("%a %l:%M %p")
  end

  def formatted_end
    (start_time + duration.minutes).strftime("%l:%M %p")
  end

  def start_datetime
    day + start_time.seconds_since_midnight.seconds
  end

  def time_until_start
    remaining_seconds = (start_time - Time.zone.now)

    days = (remaining_seconds / 86400).floor
    hours = ((remaining_seconds - days * 86400) / 3600).floor
    minutes = ((remaining_seconds - days  * 86400 - hours * 3600) / 60).floor
    {days: days, hours: hours, minutes: minutes}
  end

  def formatted_time_until_start
    from_now = time_until_start.reduce([]) do |memo, (key,value)|
      memo << "#{value}#{key[0]}" if value > 0
      memo
    end.join(" ")
  end

  def formatted_time
    "#{formatted_start} / #{formatted_end} Eastern"
  end

  def formatted_time_until
     "starts in #{formatted_time_until_start}"
  end

  def reserve_url
    "#{ENV['HOST_URL']}/matches/#{id}/reserve"
  end

  def announce
    notifier.announce_match(self)
    notifier.mention_match_for_interested(host, game.interested)
  end

  private
  def notifier
    @notifier ||= Notifications.new(self.webhook)
  end

  def generate_name
    random = Random.new(1337)
    matches_count = Match.count
    self.name = [MATCH_ADJECTIVES, MATCH_NOUNS].reduce([]) do |memo, words|
      memo << words.shuffle(random: random)[matches_count]
    end.join(" ")
  end

  def reserve_host
    reservations.create(user: host)
  end

end

app/controllers/matches_controller.rb
class MatchesController < ApplicationController
  before_action :authenticate

  def index
    @recent_matches = Match.where("start_time <= ?", Time.now)
    @matches = Match.where("start_time > ?", Time.now)
  end

  def new
    @game = Game.find_by(slug: params["game"]) || nil
    @games = Game.all - [@game]
    @guild_hooks = Webhook.with_guilds(current_user.discord_api.guilds) if @game
    @match = Match.new(game: @game)
  end

  def create
    @match = Match.create(match_params.merge(host: @current_user))

    if @match.errors.present?
      render "new"
    else
      @match.announce
      redirect_to match_path(@match)
    end
  end

  def show
    @match = Match.where("id = ?", params["id"].to_i).includes(reservations: [:user]).first
  end

  def reserve
    @match = Match.find(params["match_id"])
    @match.reserve(current_user)
    redirect_to match_path(@match)
  end

  def relinquish
    @match = Match.find(params["match_id"])
    @match.relinquish(current_user)
    redirect_to match_path(@match)
  end

  private

  def match_params
    params.require(:match).permit(:game_id, :webhook_id, :slots, :start_time, :duration, :description)
  end
end

app/views/matches/_empty_slot.html.erb
<% ringer ||= false %>
<a href="<%= match_reserve_path(@match) %>">
  <div class="empty <%= ringer ? 'ringer' : '' %>">
    <div class="avatar"></div>
    <div class="name"><%= ringer ? 'ringer' : 'open' %></div>
  </div>
</a>

app/views/matches/_game_form.html.erb
<% @match.start_time = Match::DEFAULT_START %>
<%= form_with model: @match, class: "form" do |f| %>
  <%= f.hidden_field(:game_id, value: @game.id) %>

  <div class="fields">
    <div class="basic-fields">
      <div>
        <%= label_tag(:match_slots) do %>
          Slots
        <% end %>
        <%=
          f.number_field :slots,
            value: @game.defaults["slots"],
            placeholder: @game.defaults["slots"],
            in: 2..@game.defaults["max"], step: 1
        %>
      </div>

      <div>
        <%= label_tag(:match_start_time) do %>
          Start time (Eastern)
        <% end %>
        <%= f.datetime_field :start_time, {min: Time.zone.today, max: Time.zone.today + 7.days}%>
      </div>

      <div>
        <%= label_tag(:match_duration) do %>
          Duration (mins)
        <% end %>
        <%= f.number_field :duration, placeholder: 60, value: 60, in: 15..3600 %>
      </div>
    </div>

    <div class="description">
      <%= label_tag(:match_description) do %>
      Description! Game mode, connect info, players needed, etc.
      <% end %>
      <%= f.text_area :description, value: @game.defaults["description"], size: "60x8" %>
    </div>

    <div class="webhook">
      <%= label_tag(:match_webhook_id) do %>
        Send Announcement To:
      <% end %>
      <% options = grouped_options_for_select(@guild_hooks.map{|g| [g.name, g.hooks.map{|h| [h.name, h.id]}]}) %>
      <%= f.select :webhook_id, options  %>
      <div class="notice">
        Please make sure you are actually in this channel...
        spammers will be prosecuted to the full extent of the law.
      </div>
    </div>

    <%= f.submit "Create Match & Notify Gamers" %>
  </div>

<% end %>

app/views/matches/_game_select.html.erb
<% small ||= false %>
<div
  class="games <%= small ? 'small' : '' %>"
  style="grid-template-columns: <%= small ? "1fr 1fr 1fr" : ("1fr " * @games.length)  %>;"
>
  <% @games.each do |game| %>
    <% selected = @game && @game.slug === game.slug %>
    <div class="game <%= selected ? 'selected' : '' %>">
      <a href="<%= selected ? "#" : new_match_path(game: game.slug) %>">
        <img src="<%= image_path('games/'+game.slug+'.webp') %>">
        <h3><%= small ? game.slug : game.name %></h3>
      </a>
    </div>
  <% end %>
</div>

app/views/matches/_slot.html.erb
<% ringer ||= false %>
<% me ||= false %>
<div class="player <%= ringer ? 'ringer' : '' %> <%= me ? 'me' : '' %>">
  <img class="avatar" src="<%= player.picture ? player.picture : asset_url('logo.png')  %>" alt="avatar">
  <div class="name">
    <%= player.username %>
  </div>
</div>

app/views/matches/index.html.erb
<h2>Upcoming... </h2>
<% @matches.each do |match| %>
  <h1><%= match.game.name %></h1>
  <h2>Slots Left: <%= match.slots_remaining %></h2>
<% end %>

<hr>

<h2>Recently... </h2>
<% @recent_matches.each do |match| %>
  <h1><%= match.game.name %></h1>
  <h2>Slots Left: <%= match.slots_remaining %></h2>
<% end %>

app/views/matches/new.html.erb
<div class="new-match">
  <% if @game %>
    <div class="match">

      <div class="selected-game">
          <img src="<%= image_path('games/'+@game.slug+'.webp') %>">
          <h2>Let's Play <strong><%= @game.name %>!</strong></h2>

          <%= render partial: "game_form" %>
      </div>

      <div class="sidebar">

        <div class="instructions">
          <h3>Hankering for some teamplay?</h3>

            <ol>
              <li>
                Modify the prefilled description with relevant info and it will be
                sent to Discord.
              </li>
              <li>
                You will be given the first slot automatically and a notification
                will be sent to Discord.
              </li>
              <li>
                Everyone interested in that game will be notified
                and can join by clicking the link in Discord.
              </li>
            </ol>

          <p>
            Thanks for planning ahead!
          </p>
          <p>
            <strong>GLHFDD</strong>
          </p>
        </div>

        <div class="others">
          <div class="title">Other Games</div>
          <%= render partial: "game_select", locals: {small: true} %>
        </div>
      </div>
    </div>



  <% else %>
    <%= render partial: "game_select" %>
  <% end %>
</div>

app/views/matches/show.html.erb
<div class="match-page">
  <div class="title">
    <h1 class="match-name"><%= @match.name %></h1>
  </div>

  <div class="info">
    <h2 class="game-name"><%= @match.game.name %></h2>

    <div class="start">
      <span><strong><%= @match.formatted_start %></strong></span>
      until
      <span><strong><%= @match.formatted_end %></strong></span>

      <% if @match.start_time > Time.zone.now %>
        <div class="starts_in">
          Starts in: <%= @match.formatted_time_until_start %>
        </div>
      <% else %>
        <div class="match_begun">
          Match has begun!
        </div>
      <% end %>
    </div>

    <div class="markdown">
      <%= Kramdown::Document.new(@match.description).to_html.html_safe %>
    </div>

    <h2><%= pluralize(@match.slots_remaining, "Slot") %> Left</h2>

    <div class="links">
      <% if @match.reserved?(@current_user) %>
        <% if @match.ringer?(@current_user) && !@match.full? %>
          <a class="reservation-link" href="<%= match_reserve_path(@match) %>">
            Put me in coach!
          </a>
        <% end %>
        <a class="reservation-link" href="<%= match_relinquish_path(@match) %>">
          Nevermind! I can't make it.
        </a>
      <% else %>
        <a class="reservation-link" href="<%= match_reserve_path(@match) %>">
          <% if @match.full? %>
            Let me know if a slot opens!
          <% else %>
            Reserve my slot!
          <% end %>
        </a>
      <% end %>
    </div>
    <% max_columns = @match.slots < 6 ? @match.slots : 6 %>
    <% player_box = 100 %>
    <div
      class="reservations"
      style="
        grid-template-columns: repeat(<%= max_columns %>, 1fr);
        max-width: <%= max_columns * 120 %>px;
      "
    >
      <% (0..@match.slots-1).each do |i| %>
        <% player = @match.players[i] %>
        <% if player %>
          <%= render partial: "slot", locals: {player: player, me: player == @current_user} %>
        <% else %>
          <%= render partial: "empty_slot" %>
        <% end %>
      <% end %>
      <% if @match.ringers.present? %>
        <% @match.ringers.each do |ringer| %>
          <%= render partial: "slot", locals: {player: ringer, ringer: true} %>
        <% end %>
      <% else %>
        <% if @match.full? %>
          <%= render partial: "empty_slot", locals: {ringer: true} %>
        <% end %>
      <% end %>
  </div>
  </div>
</div>