config/routes.rb
Rails.application.routes.draw do
  root "application#index"

  get "login", to: redirect("/auth/discord"), as: "login"
  get "logout", to: "sessions#destroy", as: "logout"
  get "auth/:provider/callback", to: "sessions#create"
  get "auth/failure", to: "application#index"
  get "me", to: "me#show", as: "me"

  resources :matches, only: %w(show index new create) do
    get "reserve", to: "matches#reserve"
    get "relinquish", to: "matches#relinquish"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user

  def authenticate
    unless user_signed_in?
      session[:return_to] = request.env["PATH_INFO"]
      redirect_to root_path
    end
  end

  def no_auth_allowed
    redirect_to "/matches" if user_signed_in?
  end

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def user_signed_in?
    !!current_user
  end

  def index
    no_auth_allowed
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/_header.html.erb
<div class="header">
  <img src="<%= image_path("animated-square.gif") %>" alt="logo" class="logo">
  <h1>Fathom Pickup</h1>

  <% if @current_user %>
    <div class="navbar">
      <a href="<%= matches_path %>">Matches</a>
      <a href="<%= new_match_path %>">New Match</a>
      <a href="/logout">Logout (<%= @current_user.username %>)</a>
    </div>
  <% end %>
</div>

app/views/application/index.html.erb
<div class="splash">

  <a class="login-with-discord" href="/auth/discord?origin=<%= session[:return_to] %>">
    Login with
    <img src="<%= image_path('discord.svg') %>" alt="discord-logo">
  </a>

</div>